[package]
name = "lazy-buffer"
version = "0.1.0"
authors = ["Andrey Vlasov <vlasov-andrey.oui@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
